version: '3'
volumes:
  dados:
networks:
  db:
  web:
services: 
  db: 
    image: postgres:9.6
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      #- ./dados:/var/lib/postgresql/data
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - db
  web:
    image: nginx:1.13
    volumes:
      #site
      - ./web:/usr/share/nginx/html
      #proxy reverso
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - web
    depends_on:
      - app
  app:
    image: python:3.7.2
    volumes:
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
    networks:
      - db
      - web
    depends_on:
      - db
    #ports:
    #  - 8080:8080